#!/usr/bin/env bash
# Shim for https://pypi.org/project/cloudvm
# --quiet to suppress "is already on your PATH and installed at ... Downloading and running anyway." warning
exec pipx run --quiet cloudvm "$@"
