#!/bin/bash

linelimit=${1:-138}
linelimit="$(for i in `seq 0 $linelimit`; do echo -n .; done)"

{
    if [ "$NOTRIMLINES" = "" ]; then
	sed -ue "s/^\($linelimit\).\{5,\}$/\1 .../g"
    else
	sed -u
    fi
} | \
    stdbuf --output=L awk '{  system("{ date \"+%Y-%m-%d %H:%M:%S\"; echo \":\t\"; } | tr -d \"\n\" "); print; }';
