#!/bin/bash

[ $# -ne 1 ] && {
    echo "Usage: $0 <ip>" >&2
    exit 1
}

wget -q -O - \
    "http://www.geobytes.com/IpLocator.htm?GetLocation&template=php3.txt&IpAddress=$1" \
    | grep '^<meta ' \
    | sed 's@^<meta\s\+name="\([^"]*\)"\s\+content="\([^"]*\)"\s*/\?>[ \t\r]*$@\1: \2@'
