#!/bin/bash -e

program_name="$(basename "$0")"
green='\e[0;32m'
red='\e[0;31m'
end_color='\e[0m'

ex() {
    echo -e "${green}+ $*${end_color}"
    "$@"
}

err() {
    echo -e "${red}${program_name}: $*${end_color}" >&2
}

ex git fetch --prune --tags origin \
    || ex git fetch --prune --tags \
        "$(git rev-parse --abbrev-ref --symbolic-full-name @{u} | cut -d/ -f1)"

# Check for 'dirty' state (and fail). If clean, remote 1 last commit.
ex git update-index -q --ignore-submodules --refresh
ex git diff-files --quiet --exit-code --ignore-submodules -- \
    && ex git diff-index --quiet --exit-code --cached HEAD --ignore-submodules -- \
    || {
        err "You have staged or unstaged changes."
        err "Please commit or stash them."
        ex git status
        exit 1
    }

upstream_branch="$(git rev-parse --abbrev-ref --symbolic-full-name '@{u}')"
if [ "$(git rev-parse HEAD)" = "$(git rev-parse "${upstream_branch}")" ]; then
    err "No new changes upstream (${upstream_branch}) and no local changes to revert"
else
    ex git reset --hard "${upstream_branch}"
fi

ex git --no-pager log --oneline -n6
