#!/bin/bash -e

green='\e[0;32m'
end_color='\e[0m'

ex() {
    echo -e "${green}+ $*${end_color}"
    "$@"
}

ex git fetch --prune --tags origin \
    || ex git fetch --prune --tags \
        "$(git rev-parse --abbrev-ref --symbolic-full-name @{u} | cut -d/ -f1)"

# Check for 'dirty' state (and fail). If clean, remote 1 last commit.
ex git rebase --onto HEAD~1 HEAD || {
    ex git status
    exit 1
}
ex git reset --hard "$(git rev-parse --abbrev-ref --symbolic-full-name @{u})"
ex git --no-pager log --oneline -n6
