#!/bin/bash

set -euo pipefail

declare -a push_opts
remote=''
for i; do
    case $i in
        -*)
            push_opts+=("$i");;
        *)
            if [ "$remote" != "" ]; then
                echo "`basename $0`: remote specified twice." >&2
                exit 1
            fi
            remote="$i";;
    esac
done

test "$remote" != "" || remote="origin"

br="$(git symbolic-ref HEAD)"
exec git push "$remote" "$br" ${push_opts[@]+"${push_opts[@]}"}
