#!/bin/bash

if test $# -ge 1; then
    fixup_commit="$1"; shift
    git commit --no-verify --fixup="${fixup_commit}" "$@"
else
    echo "Usage: $0 <commitish> [options for git commit]" >&2
    exit 1
fi
