#!/bin/bash

set -euo pipefail

declare -a push_opts
remote=''
for i; do
    case $i in
        -*)
            push_opts+=("$i");;
        *)
            if [ "$remote" != "" ]; then
                echo "`basename $0`: remote specified twice." >&2
                exit 1
            fi
            remote="$i";;
    esac
done

branch="$(git name-rev --name-only HEAD)"
test "$remote" != "" || remote="$(git config "branch.$branch.remote")"
git push "$remote" "$branch" ${push_opts[@]+"${push_opts[@]}"}
