#!/bin/bash

set -euo pipefail

green=$'\e[0;32m'
end_color=$'\e[0m'

ex() {
    echo "${green}+ $(printf '%q ' "$@" | sed 's/ $//')${end_color}" >&2
    "$@"
}

declare -a push_opts
remote=''
for i; do
    case $i in
        -*)
            push_opts+=("$i");;
        *)
            if [ "$remote" != "" ]; then
                echo "`basename $0`: remote specified twice." >&2
                exit 1
            fi
            remote="$i";;
    esac
done

branch="$(git symbolic-ref HEAD | sed 's@^refs/heads/@@')"
test "$remote" != "" || remote="$(git config "branch.$branch.remote")"
ex git push "$remote" "$branch" ${push_opts[@]+"${push_opts[@]}"}
