#!/bin/bash

set -e

green=$'\e[0;32m'
end_color=$'\e[0m'

ex() {
    echo "${green}+ $(printf '%q ' "$@" | sed 's/ $//')${end_color}" >&2
    "$@"
}

branch="$(git symbolic-ref HEAD)"
remote="$(git config "branch.$(sed 's@^refs/heads/@@' <<< "$branch").remote")"
default_branch="$(git config --default master --get findepi.default-branch)"

ex git push "$remote" --delete "$branch"
ex git checkout "${default_branch}"
ex git branch -D @{-1}
