#!/bin/bash -xe

export DISPLAY="$(echo "${DISPLAY:-:0}" | cut -d . -f 1)"
dumpdir=~/tmp/"`basename $0`$DISPLAY"
mkdir -p "$dumpdir"
dumpfile="$dumpdir/$(date +%Y-%m-%d-%H:%M).jpg"

findimages() {
    find "$dumpdir" \( -name '*.png' -o -name '*.jpg' \) "$@"
}

{
    flock -w 3 9
    date >&9
    echo pid=$$ >&9

    if test "$(findimages -cmin -1 | \
            wc -l)" -ge 2; then
        echo "Too many recent files in \`$dumpdir'." >&2
        findimages -cmin 1 -delete \
            -printf "Deleted recent extranouos file \`%p'.\n"
        #exit 1
    fi

    findimages -ctime +0 -delete -printf "Deleted old screen shot \`%p'.\n"
    findimages -empty -delete -printf "Deleted empty screen shot \`%p'.\n"

    #xset b 0 0 0
    #import -window $(xwininfo -root | grep xwininfo:\ Window\ id: | awk '{print $4}') png:-
    xwd -root -silent | \
        xwdtopnm | \
        pnmscale -xysize 800 600 | \
        pnmtojpeg > "$dumpfile"
    echo "Saved \`$dumpfile'."

} 9> "$dumpdir/.lock"

exit 0
