#!/bin/bash
# vim:tw=0

SOURCES_EXTENSIONS='h|hpp|c|cc|sh|hs|pl|py|cpp|java|xml|html|js|css|po|sql|proto|txt|rules|conf|tex|yml|php'

if [ "$1" = '-git' ]; then
    shift;
    git ls-tree -r --name-only HEAD "${@:-.}" \
        | exec grep -E "(^|/)(Makefile|[^/]+\\.($SOURCES_EXTENSIONS))\$"
fi

exec find -H ${@:-.} -regextype posix-egrep '(' -type d -regex '(.*/)+(\.[^/]+|_darcs|django|django-([a-zA-Z]+-)*trunk|CVS|build)' -prune -false ')' \
    -o -type f -a -iregex "(.*/)?(Makefile|[^/]+\\.($SOURCES_EXTENSIONS))"
