#!/bin/bash
# vim:tw=0 nobk

SOURCES_EXTENSIONS='h|hpp|c|cc|sh|hs|pl|py|cpp|java|xml|html|js|css|po|sql|proto|txt|rules|conf|tex|yml|php'

if [ "$1" = '-git' ]; then
    shift;
    set -o pipefail
    git ls-tree -r --name-only HEAD "${@:-.}" \
        | grep -E "(^|/)(Makefile|cron-[^~/]+|[^/]+\\.($SOURCES_EXTENSIONS))\$"
    exit
fi

exec find -H ${@:-.} -regextype posix-egrep '(' -type d -regex '(.*/)+(\.[^/]+|_darcs|django|django-([a-zA-Z]+-)*trunk|CVS|build)' -prune -false ')' \
    -o -type f -a -iregex "(.*/)?(Makefile|cron-[^/~]+|[^/]+\\.($SOURCES_EXTENSIONS))"
