#!/usr/bin/env python

import os
import subprocess

def run(*args, **kwargs):
    retcode = subprocess.Popen(*args, **kwargs).wait()
    if retcode != 0:
        raise Exception("Subprocess returned %r." % retcode)

os.chdir(os.path.dirname(__file__))
run(['make', 'everything'])
run(['make', 'postupdate'])

